# -*- coding: utf-8 -*-
"""Loan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbRmwmDYd3GQnqwHtgLiiEh95v_INxj0
"""

print("Simulação de um empréstimo: ")
salary = float(input("\nInsira seu salário ($): "))
age = float(input("Insira sua idade: "))
if salary>1200 and 80>age>=18:
    print("\nInfelizmente voce está apto para o empréstimo!!!")
    money = float(input("\nInsira o valor do empréstimo ($): "))
    time = float(input("Insira o prazo (máximo 120 meses): "))
    parc_loan = salary * (30/100)
    IOF = (money * (38/10000)) + (money * 84/1000000 * ((time/12)*365))
    tax = IOF + (155/10000) * money * time
    month_parc = (money + tax)/time
    if month_parc<=parc_loan:
        print("\nParabéns, seu empréstimo foi aprovado!!!")
        print(f"\nParcela de ${month_parc:.2f} durante {time:.0f} meses")
    else:
        print("\nSeu empréstimo não foi aprovado")
else:
    print("\nVoce não está apto para o empréstimo")